# Generated by Django 5.1.4 on 2024-12-27 07:50

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(default=accounts.models.generate_token, max_length=6, unique=True),
        ),
    ]
