# Generated by Django 5.2 on 2025-05-02 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 3, 16, 10, 17, 815626, tzinfo=datetime.timezone.utc)),
        ),
    ]
