# Generated by Django 5.1.4 on 2025-01-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_passwordresettoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(blank=True, help_text='The secret key for TOTP authentication', max_length=16, null=True),
        ),
    ]
