# Generated by Django 5.2 on 2025-05-07 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_profile_image_user_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 8, 12, 11, 18, 995374, tzinfo=datetime.timezone.utc)),
        ),
    ]
