# Generated by Django 5.2 on 2025-05-07 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 8, 12, 15, 20, 452902, tzinfo=datetime.timezone.utc)),
        ),
    ]
