# Generated by Django 5.2 on 2025-05-12 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 13, 10, 10, 37, 87073, tzinfo=datetime.timezone.utc)),
        ),
    ]
