# Generated by Django 5.2 on 2025-05-13 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 14, 8, 31, 15, 834624, tzinfo=datetime.timezone.utc)),
        ),
    ]
