# Generated by Django 5.2 on 2025-05-25 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 26, 14, 20, 38, 461702, tzinfo=datetime.timezone.utc)),
        ),
    ]
