# Generated by Django 5.1.4 on 2025-01-07 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_user_otp_code_user_otp_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp_secret',
        ),
        migrations.RemoveField(
            model_name='user',
            name='two_factor_enabled',
        ),
    ]
