# Generated by Django 5.1.7 on 2025-05-26 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_passwordresettoken_expires_at_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 27, 14, 6, 33, 528145, tzinfo=datetime.timezone.utc)),
        ),
    ]
