# Generated by Django 5.1.7 on 2025-06-01 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 2, 10, 54, 47, 703322, tzinfo=datetime.timezone.utc)),
        ),
    ]
