# Generated by Django 5.1.4 on 2025-01-12 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_otp_secret'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='otp_secret',
            new_name='totp_key',
        ),
    ]
