# Generated by Django 5.1.4 on 2025-02-04 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_passwordresettoken_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 5, 13, 43, 1, 293833, tzinfo=datetime.timezone.utc)),
        ),
    ]
