# Generated by Django 5.1.7 on 2025-03-19 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_is_2fa_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 20, 10, 4, 47, 356666, tzinfo=datetime.timezone.utc)),
        ),
    ]
